---
title: "統計計算_hw0528"
author: "農藝所碩二 R08621110 閻大瑞"
date: "2021/5/27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. 
#### target function
```{r}
target <- function(x) {
  sigma <- 1
  value <- (x/sigma^2)*exp(-x^2/(2*sigma^2))
  return(value)
}
```

#### Metropolis-Hastings sampler
```{r}
metro <- function(initial = 1, iter = 10000, burnin = 2000) {
  chain <- c(initial)
  for (i in 1:iter) {
    proposal <- rgamma(1, chain[i], 1)
    ratio <- (target(proposal)*dgamma(chain[i], proposal, 1)) / (target(chain[i])*dgamma(proposal, chain[i], 1))
    ifelse(runif(1)<ratio, chain[i+1] <- proposal, chain[i+1] <- chain[i])
  }
  chain <- chain[-c(1:burnin+1)]
  return(chain)
}
```

#### sample distribution
```{r}
result1 <- metro()

hist(result1, main = "distribution", breaks = 20, freq = F)
curve(target, 0, 4, add = T)
```

#### convergence
```{r}
plot(result1, type = "l", main = "convergence")
```



## 2. 
#### bivariate density
```{r}
f <- function(x, y, a, b, n) choose(n, x)*(y^(x+a-1))*((1-y)^(n-x+b-1))
```

#### Gibbs sampler
```{r}
gibbs <- function(a = 5, b = 5, n = 9, target = f, x_init = 5, y_init = 0.5, iter = 10000, burnin = 2000, thin = 2) {

  data <- matrix(NA, iter+1, 3)
  data[1,] <- c(x_init, y_init, f(x_init, y_init, a = a, b = b, n = n))
  for (i in 1:iter) {
    data[i+1,1] <- rbinom(1, n, data[i,2])
    data[i+1,2] <- rbeta(1, data[i+1,1]+a, n-data[i+1]+b)
    data[i+1,3] <- f(data[i+1,1], data[i+1,2], a = a, b = b, n = n)
  }
  
  data <- data[-c(1:burnin+1),]
  index <- seq(1, nrow(data), thin)
  data <- data[index,]

  return(data)
}
```


#### joined distribution
```{r}
chain1 <- gibbs()

plot(chain1[,1], chain1[,2], xlab = "x", ylab = "y")
hist(chain1[,3], main = "bivariate distribution", xlab = "f(x,y)")
```

#### convergence
```{r}
plot(chain1[,3], type = "l", main = "convergence", ylab = "f(x,y)")
```

#### Gelman-Rubin convergence method
```{r}
gelman <- function(data) {
  
  chain_mean <- rowMeans(data)
  B <- ncol(data)*var(chain_mean)
  chain_var <- apply(data, 1, var)
  W <- mean(chain_var)*(ncol(data)-1)*(1/(ncol(data)*nrow(data)))
  Varhat <- ((ncol(data)-1)/ncol(data))*W + (1/ncol(data))*B
  Rhat <- Varhat/W
  
  return(Rhat)
}
```


```{r}
chain2 <- gibbs()
chain3 <- gibbs()
chain4 <- gibbs()
chain5 <- gibbs()
chain <- matrix(c(chain1[,3], chain2[,3], chain3[,3], chain4[,3], chain5[,3]), 5, nrow(chain1))

gelman(chain)
```

