---
title: "統計計算_hw3"
author: "農藝所碩二 R08621110 閻大瑞"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
empirical <- function(distribution, n, replicate, mu, alpha) {
  pvalue <- c()
  for (i in 1:replicate){
    if (distribution == "chi-square") data <- rchisq(n, df = 1)
    else if (distribution == "uniform") data <- runif(n, min = 0, max = 2)
    else if (distribution == "exponential") data <- rexp(n, rate = 1)
    else {
      data <- rep(0, times = n)
      warning("undifined distribution")
    }
    ttest <- t.test(data, alternative = "two.sided", mu = mu)
    pvalue[i] <- ttest$p.value
  }
  phat <- mean(pvalue < alpha)
  return(phat)
}
```

## (1) $\chi^2$ (1)
```{r}
n <- seq(10, 60, 10)
mu1 <- 1
result1 <- c()

for (i in 1:length(n)) {
  result1[i] <- empirical(distribution = "chi-square", n = n[i], replicate = 10000, mu = mu1, alpha = 0.05)
}
result1
```

## (2) uniform (0,2)
```{r}
n <- seq(10, 60, 10)
mu2 <- 1
result2 <- c()

for (i in 1:length(n)) {
  result2[i] <- empirical(distribution = "uniform", n = n[i], replicate = 10000, mu = mu2, alpha = 0.05)
}
result2
```

## (3) exponential ($\lambda$ = 1)
```{r}
n <- seq(10, 60, 10)
mu3 <- 1
result3 <- c()

for (i in 1:length(n)) {
  result3[i] <- empirical(distribution = "uniform", n = n[i], replicate = 10000, mu = mu3, alpha = 0.05)
}
result3
```

## plot
```{r}
n <- seq(10, 60, 10)
plot(n, result1, , type = "b", lwd = 2, col = 1, main = "Empirical Type I Error Rate", ylim = c(0, 0.14), ylab = bquote(alpha))
lines(n, result2, type = "b", lwd = 2, col = 2)
lines(n, result3, type = "b", lwd = 2, col = 3)
legend("topright", lwd = 2, col = 1:3, , legend = c("chi-square", "uniform (0,2)", "exp (lambda = 1)"))
```
由以上結果可以推論，來自uniform和exponential分布的樣本不論在樣本較小(n=10)或者樣本較大(n=60)的情況下都可以得到非常接近給定顯著水準之type I error；而來自卡方分布的樣本利用t-test檢定則近似的較差，type I error總是比給定的顯著水準明顯來得大，即使在樣本較大的情形下仍有一些差距。
